### ISSUE TITLE
Addition of nouveau drivers and corelating mesa package for nvk

### ISSUE THREAD

**Issue by Fletscherrrr** [kkrruumm/void-install-script#3]
First of all I want to say thank you for your work, this installer has definitely come a long way and I'm looking forward to witness further progression. (The implementation of your module system is very neat btw.)

As for the actual topic: 
As you may know nouveau + nvk has seen a lot of good and important progress in the past months. So much so that I'd say its actually a valid alternative to the proprietary nvidia drivers in my opinion and I'd guess that it's only getting better moving forward. I've been on the nouveau drivers for a few weeks now and I have to say that it seems generally stable. 

It might be worth to consider at the very least.

**Comment by kkrruumm** [comment]
Hey, I can absolutely look into nvk and most likely add it as an option, though unfortunately I don't have a great way to test this. My goal here isn't *always* to provide upmost stability (see: efistub on some motherboards), so I'll look into this and get back to this issue shortly.

Also, I appreciate the kind words!

**Comment by kkrruumm** [comment]
@Fletscherrrr Alright, seeing as there is no package in the Void repository for vulkan-nouveau (or its lib32), that's a bit of a showstopper. Of course, if a Void source package exists already that just isn't in the repo, that could still be fine. What did you do to achieve your setup, just pull the source from the mesa gitlab?

**Comment by kkrruumm** [comment]
Yeah, didn't find those packages in the repos. This feature has been added, though I've marked it as experimental in the installer for now given that I have no way to test this. Do let me know if there's anything else, closing with this comment.

**Comment by Fletscherrrr** [comment]
Just triple checked I didn't sell you any crap but to make sure the packages are available in the standard repo.
Also tested the setup on a second machine and it should work as expected though `mesa-nouveau-dri` and `mesa-nouveau-dri-32bit` are marked as "transitional packages" so I guess they will somehow change in the future(?)

Well anyway thanks again for your time man. I really appreciate your efforts!

**Comment by kkrruumm** [comment]
> `mesa-nouveau-dri` and `mesa-nouveau-dri-32bit` are marked as "transitional packages" so I guess they will somehow change in the future(?)

These packages are transitional in the sense of pointing back at the normal mesa package, which has definitions for all of these packages instead of having split package templates for all of them, it should be fine. Also, no worries at all! @Fletscherrrr
