### ISSUE TITLE
[feature request] separate UI to module

### ISSUE THREAD

**Issue by zen0bit** [kkrruumm/void-install-script#5]
I like your installer 👍

Using void daily..

Also created some installers my self and contribute to other installers project. But your is first modular 👍

I like creating UI's, with different tools (yad, easybashgui, gum..)

I wanna create UI modules for your script.

And learn about module structure bash scripting from you.. ❤️

for [quickemu](https://github.com/quickemu-project/quickemu) and my future scripts

PS: Don't want replace default UI, rather add options to choose from any UI module TUI or GUI

**Comment by kkrruumm** [comment]
Making the UI modular in this script isn't something I really intend on doing, as Dialog seems good enough(?) and it would require a pretty major amount of effort. Of course, if your goal here is to create modules that have a different UI to be used with this installer with the existing modules system, that should already be doable as you are free to run any commands you'd like within the main() function of your module, including installing another UI solution and then using that instead with your module.
