### ISSUE TITLE
keyboard layout and locale selection

### ISSUE THREAD

**Issue by djgs01** [kkrruumm/void-install-script#7]
Hi 👋🏻,

First off, congrats on your awesome script! I really love how you’ve set everything up to make installing Void Linux so easy.

Also, do you think it might be worth adding options to the script for selecting the keyboard layout and system locale? Right now, I just edit the installer.sh file and change the "locale" and "liblocale" variables, but it feels a bit tedious.

Thanks! 🙂

**Comment by kkrruumm** [comment]
hey, sorry for getting back to you on this so late

yeah, this was a bit of an oversight of mine, i'll try and fix this as soon as possible because it counts as the installer not doing what it's intended to do, that being to deploy a ready to go system without fuss

**Comment by kkrruumm** [comment]
hey,

got a day off of work so got around to adding a locale selection section, the menu is a bit annoying, but the option is there now.

if there's anything else, do let me know, closing with this issue.
